#spring.datasource:
#  url: jdbc:h2:mem:testdb
#  driverClassName: org.h2.Driver
#  username: sa
#  password: password

spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2
